### ISSUE TITLE
Convert  the annotations into PASCAL-VOC format

### ISSUE THREAD

**Issue by chenmw269** [tdchaitanya/MMTOD#3]
I use the scripts in the generate_annotations folder, but no XML file is produced after the program is run. and here's what happens
![image](https://user-images.githubusercontent.com/57318837/88187444-1be75800-cc69-11ea-871e-3fc2e65e6d62.png)
I downloaded the FLIR dataset. The contents of the "train" folder are shown below.
![image](https://user-images.githubusercontent.com/57318837/88187975-ccedf280-cc69-11ea-990e-40e2dd68adb6.png)

In which step did I go wrong？

**Comment by MoatazElTahan** [comment]
Same here also

**Comment by MoatazElTahan** [comment]
Same here also but I could fix it and I fixed a couple of issues in the script and then made a pull request for the changes

**Comment by chenmw269** [comment]
> Same here also but I could fix it and I fixed a couple of issues in the script and then made a pull request for the changes

Thanks! I still have a question, which folder is the RGB images saved through the CycleGAN or UNIT? Or haven't it been preserved? How can I save the converted RGB images?
